import { Resource } from "@/types/content"

export const RESOURCES: Resource[] = [
    // Essential - Official exam materials
    {
        id: 'res-001',
        title: 'NHA CEHRS Test Plan (Blueprint)',
        url: 'https://www.nhanow.com/docs/default-source/test-plans/nha_cehrs-test-plan.pdf',
        resourceType: 'pdf',
        category: 'essential',
        description: 'Official exam blueprint listing all domains, task statements, and knowledge statements. Your master checklist for exam prep.',
        isExternal: true,
        domainTags: ['all'],
    },
    {
        id: 'res-002',
        title: 'NHA Candidate Handbook',
        url: 'https://knowledge.nhanow.com/nha-candidate-handbook',
        resourceType: 'official',
        category: 'essential',
        description: 'Eligibility, registration, scoring, retakes, and policies for all NHA exams.',
        isExternal: true,
        domainTags: ['exam-prep'],
    },
    {
        id: 'res-003',
        title: 'NHA CEHRS Certification Page',
        url: 'https://www.nhanow.com/certification/nha-certifications/certified-electronic-health-records-specialist-%28cehrs%29',
        resourceType: 'official',
        category: 'essential',
        description: '5 steps to certification overview. Eligibility requirements, test time, and fees.',
        isExternal: true,
        domainTags: ['exam-prep'],
    },

    // Deep Dive - Comprehensive learning resources
    {
        id: 'res-004',
        title: 'HealthIT.gov - What are EHRs?',
        url: 'https://www.healthit.gov/topic/health-it-and-health-information-exchange-basics/what-are-electronic-health-records-ehrs',
        resourceType: 'article',
        category: 'deep-dive',
        description: 'Comprehensive overview of Electronic Health Records from the Office of the National Coordinator.',
        isExternal: true,
        domainTags: ['non-clinical', 'clinical'],
    },
    {
        id: 'res-005',
        title: 'HealthIT.gov - Benefits of EHRs',
        url: 'https://www.healthit.gov/topic/health-it-and-health-information-exchange-basics/benefits-ehrs',
        resourceType: 'article',
        category: 'deep-dive',
        description: 'Official documentation of EHR benefits for healthcare organizations.',
        isExternal: true,
        domainTags: ['non-clinical'],
    },
    {
        id: 'res-006',
        title: 'EHR Playbook',
        url: 'https://www.healthit.gov/playbook/electronic-health-records/',
        resourceType: 'course',
        category: 'deep-dive',
        description: 'Implementation and operations playbook covering workflows, optimization, and reporting.',
        isExternal: true,
        domainTags: ['non-clinical', 'reporting'],
    },
    {
        id: 'res-007',
        title: 'CMU OLI - Healthcare IT Foundations',
        url: 'https://oli.cmu.edu/courses/health-information-technology-foundations-open-free/',
        resourceType: 'course',
        category: 'deep-dive',
        description: 'Free structured online course covering healthcare delivery, payment systems, roles, and regulations.',
        isExternal: true,
        domainTags: ['non-clinical', 'revenue-cycle'],
    },

    // Official - HIPAA & Compliance
    {
        id: 'res-008',
        title: 'HHS HIPAA Training & Resources',
        url: 'https://www.hhs.gov/hipaa/for-professionals/training/index.html',
        resourceType: 'official',
        category: 'official',
        description: 'Official HIPAA overview and free training tools from the Department of Health & Human Services.',
        isExternal: true,
        domainTags: ['compliance'],
    },
    {
        id: 'res-009',
        title: 'HHS HIPAA Security Rule Guidance',
        url: 'https://www.hhs.gov/hipaa/for-professionals/security/guidance/index.html',
        resourceType: 'official',
        category: 'official',
        description: 'Technical safeguards, administrative safeguards, and physical safeguards guidance.',
        isExternal: true,
        domainTags: ['compliance'],
    },
    {
        id: 'res-010',
        title: 'Free HIPAA Training (AccountableHQ)',
        url: 'https://www.accountablehq.com/free-hipaa-training',
        resourceType: 'course',
        category: 'deep-dive',
        description: 'Free HIPAA training course with certificate upon completion.',
        isExternal: true,
        domainTags: ['compliance'],
    },

    // Practice - Hands-on and testing
    {
        id: 'res-011',
        title: 'Free EHR Simulation Systems',
        url: 'https://www.healthysimulation.com/free-ehr-healthcare-simulation/',
        resourceType: 'practice',
        category: 'practice',
        description: 'Curated list of free EHR simulators for hands-on practice with clinical workflows.',
        isExternal: true,
        domainTags: ['clinical', 'non-clinical'],
    },
    {
        id: 'res-012',
        title: 'Chartflow Free EHR Simulation',
        url: 'https://blog.chartflow.io/posts/free-ehr-simulation-for-students',
        resourceType: 'practice',
        category: 'practice',
        description: 'Interactive EHR simulation designed for students learning clinical documentation.',
        isExternal: true,
        domainTags: ['clinical'],
    },
    {
        id: 'res-013',
        title: 'Free CEHRS Practice Test',
        url: 'https://take.quiz-maker.com/cp-np-free-cehrs-practice-test',
        resourceType: 'practice',
        category: 'practice',
        description: 'Free practice test with questions similar to the actual CEHRS exam.',
        isExternal: true,
        domainTags: ['exam-prep'],
    },
    {
        id: 'res-014',
        title: 'EHR Specialist Practice Quiz (ProProfs)',
        url: 'https://www.proprofs.com/quiz-school/story.php?title=3dq-electronic-health-records-specialist-cehrs',
        resourceType: 'practice',
        category: 'practice',
        description: 'Practice questions covering core EHR specialist competencies.',
        isExternal: true,
        domainTags: ['exam-prep'],
    },
    {
        id: 'res-015',
        title: 'CMS ICD-10-CM Training',
        url: 'https://www.cms.gov/Outreach-and-Education/MLN/WBT/MLN6447308-ICD-10-CM/icd10cm/index.html',
        resourceType: 'course',
        category: 'deep-dive',
        description: 'Official CMS web-based training for ICD-10-CM diagnosis coding.',
        isExternal: true,
        domainTags: ['revenue-cycle'],
    },
]
